package DTCController;

public class DTCEnv {

  // verbal conversion for signals reference numbers
  public final static String[] sigNames = {
          "Sig_unused",
          "Unknown",
          "Unknown",
          "Unknown",
          "CoEng_rTrq__Carb_r_DLen1",
          "CTSCD_tClntLin__Carb_t_DLen1",
          "Unknown",
          "Unknown",
          "Unknown",
          "Unknown",
          "Unknown",
          "BPSCD_pLin__Carb_p_DLen1",
          "Eng_nAvrg__Carb_n_DLen2",
          "VSSCD_v__Carb_v_DLen1",
          "Unknown",
          "IATSCD_tAirLin__Carb_t_DLen1",
          "AFSCD_dmAirRawPerTime__Carb_mAirTim_DLen2",
          "APPCD_rLinAPP1__Carb_r1_DLen2",
          "PFlt_stSecAir__OneToOne_DLen1",
          "Unknown",
          "Unknown",
          "Unknown",
          "Unknown",
          "Unknown",
          "Unknown",
          "Unknown",
          "Unknown",
          "Unknown",
          "Signals_PID0x1C_C__OneToOne_DLen1",
          "Unknown",
          "Unknown",
          "Unknown",
          "Unknown",
          "DSMDur_ctDfctDur1__Carb_l_DLen2",
          "Unknown",
          "RailCD_pPeak__Carb_p1_DLen2",
          "AFSCD_rAirNormHiEOBD__Carb_r2_DLen2",
          "AFSCD_rAirNormLoEOBD__Carb_r2_DLen2",
          "AFSCD_rAirThrHiEOBD__Carb_r2_DLen2",
          "AFSCD_rAirThrLoEOBD__Carb_r2_DLen2",
          "Unknown",
          "DSM_stSysLamp__OneToOne_DLen1",
          "DSM_stMIL__OneToOne_DLen1",
          "CTSCD_uRaw__u_DLen1",
          "CTSCD_tClnt__t_DLen1",
          "Eng_nAvrg__n_DLen2",
          "AFSCD_dmAirPerTime__mAirTim_DLen1",
          "BattCD_u__uBatt_DLen1",
          "Unknown",
          "LIGov_nSetpoint__n_DLen1",
          "VSSCD_v__v_DLen1",
          "VSSCD_a__a_DLen1",
          "InjCtl_qSet__q_DLen1",
          "EGRSCD_rLgTimeDrftNormEOBD__Carb_r2_DLen2",
          "EGRSCD_rShTimeDrftNormEOBD__Carb_r2_DLen2",
          "IATSCD_uRaw__u_DLen1",
          "IATSCD_tAir__t_DLen1",
          "BPSCD_uRawVal__u_DLen1",
          "BPSCD_pOutVal__p_DLen1",
          "AccPed_stPlaAPPBrk__OneToOne_DLen1",
          "AccPed_trqDes__trq1_DLen1",
          "HWEMon_numRecovery__stLow_DLen1",
          "EEPCD_stOptNumSet__OneToOne_DLen1",
          "Eng_nAvrg_PR__n_DLen2",
          "CTSCD_tClnt_PR__t_DLen1",
          "VSSCD_v_PR__v_DLen1",
          "InjCtl_qCurr_PR__q_DLen1",
          "Unknown",
          "FanCD_stOut__OneToOne_DLen1",
          "FanCD_rOut__r1_DLen1",
          "TVASCD_rLgTimeDrftClsdNormEOBD__Carb_r2_DLen2",
          "TVASCD_rShTimeDrftClsdNormEOBD__Carb_r2_DLen2",
          "TVASCD_rLgTimeDrftOpnNormEOBD__Carb_r2_DLen2",
          "TVASCD_rShTimeDrftOpnNormEOBD__Carb_r2_DLen2",
          "PFlt_pChrgMinNormEOBD__Carb_p2_DLen2",
          "PFlt_pChrgMaxNormEOBD__Carb_p2_DLen2",
          "EGRSCD_rLgTimeDrftThrEOBD__Carb_r2_DLen2",
          "EGRSCD_rShTimeDrftThrEOBD__Carb_r2_DLen2",
          "TVASCD_rLgTimeDrftClsdThrEOBD__Carb_r2_DLen2",
          "TVASCD_rShTimeDrftClsdThrEOBD__Carb_r2_DLen2",
          "AFSCD_mAirPerCyl__mAirCyl_DLen1",
          "AFSCD_uRaw__u_DLen1",
          "Unknown",
          "TVASCD_rLgTimeDrftOpnThrEOBD__Carb_r2_DLen2",
          "TVASCD_rShTimeDrftOpnThrEOBD__Carb_r2_DLen2",
          "ACCD_stMnSwtDebVal__OneToOne_DLen1",
          "ACCD_stPres__OneToOne_DLen1",
          "ACCD_stPresMech__OneToOne_DLen1",
          "BrkCD_stPressed__OneToOne_DLen1",
          "BrkCD_stRedSwtDebVal__OneToOne_DLen1",
          "ConvCD_stDebVal__OneToOne_DLen1",
          "ErLpCD_stMil__OneToOne_DLen1",
          "T15CD_stDebValPre__OneToOne_DLen1",
          "FrmMng_stAC__OneToOne_DLen1",
          "FrmMng_stBrk__OneToOne_DLen1",
          "AFSCD_rAirNormEOBD__Carb_r2_DLen2",
          "FrmMng_stAOHt__OneToOne_DLen1",
          "T15CD_stDebVal__OneToOne_DLen1",
          "FTSCD_tFuel__t_DLen1",
          "RailCD_pPeak__p2_DLen1",
          "APPCD_uRawAPP1__u_DLen1",
          "APPCD_uRawAPP2__u_DLen2",
          "APPCD_rFlt__r_DLen1",
          "APSCD_pVal__p_DLen1",
          "APSCD_uRaw__u_DLen1",
          "ACCD_p__p1_DLen1",
          "ASDrf_trqInr__trq_DLen1",
          "CoEng_trqInrSet__trq_DLen1",
          "PFlt_lLstRgnAvrg__l_DLen1",
          "PFlt_lLstRgn__l_DLen1",
          "PFltCD_stPresDiffOfsLrn__OneToOne_DLen1",
          "CoDT_trqDes__trq_DLen1",
          "CoDT_trqMin__trq1_DLen1",
          "CoDT_trqMax__trq1_DLen1",
          "CoVeh_trqPrpDes__trq1_DLen1",
          "CoVM_trqPrpDes__trq1_DLen1",
          "LIGov_trq__trq_DLen1",
          "Prp_trqRaw__trq1_DLen1",
          "Gearbx_trqInMax__trq_DLen1",
          "Gearbx_trqInc__trq_DLen1",
          "Gearbx_trqDec__trq_DLen1",
          "FMTC_trqInrLimSmk__trq_DLen1",
          "AirCtl_stMonitor__OneToOne_DLen1",
          "AirCtl_rEGR__r_DLen1",
          "AirCtl_rTVA__r_DLen1",
          "PCR_stMonitor__OneToOne_DLen1",
          "PCR_pDesVal__p_DLen1",
          "PCR_rGvnr__r_DLen1",
          "Rail_pSetPoint__p2_DLen1",
          "EngM_stSync__OneToOne_DLen1",
          "CoEng_stEng__OneToOne_DLen1",
          "CoEng_stAftRun__OneToOne_DLen1",
          "CoEng_stShutOff__OneToOne_DLen1",
          "CoEng_stTrqLimErr__OneToOne_DLen1",
          "Gearbx_stGear__OneToOne_DLen1",
          "ACCtl_stLogicOut__OneToOne_DLen1",
          "GlwCtl_stLampOut__OneToOne_DLen1",
          "GlwCtl_stActrOut__OneToOne_DLen1",
          "TtLpCD_stOvrHeatLamp__OneToOne_DLen1",
          "FMTC_qStrt__q_DLen1",
          "InjCrv_qPiI1Des__q_DLen1",
          "InjCrv_qMI1Des__q_DLen1",
          "InjCrv_qPoI1Des__q_DLen1",
          "InjCrv_phiPiI1Des__phi_DLen1",
          "InjCrv_phiMI1Des__phi_DLen1",
          "InjCrv_phiPoI1Des__phi_DLen1",
          "InjCtl_qCurr__q_DLen1",
          "InjCtl_qSetUnBal__q_DLen1",
          "InjCtl_qLim__q_DLen1",
          "FBC_q__q1_DLen1",
          "AFSCD_dmAirNorm__mAirTim_DLen1",
          "FTSCD_uRaw__u_DLen1",
          "OxiCCD_tPre__t1_DLen1",
          "FanCtl_rOutVal__r1_DLen1",
          "FanCtl_stOut__OneToOne_DLen1",
          "Rail_dvolMeUnSet__dvolMeUn_DLen1",
          "MRlyCD_stMon__OneToOne_DLen1",
          "InjCrv_tiPiI1Des__ti_DLen1",
          "AirCtl_mDesVal__mDesVal_DLen1",
          "CoEng_stRevShutOff__OneToOne_DLen4",
          "CoEng_stRevShutOff__ShftR8_DLen4",
          "CoEng_stRevShutOff__ShftR16_DLen4",
          "CoEng_stRevShutOff__ShftR24_DLen4",
          "FBC_qDvtCyl[0]__q1_DLen1",
          "FBC_qDvtCyl[1]__q1_DLen1",
          "FBC_qDvtCyl[2]__q1_DLen1",
          "FBC_qDvtCyl[3]__q1_DLen1",
          "PFltCD_uRawTempPre__u_DLen1",
          "Unknown",
          "PFlt_pChrgNormEOBD__Carb_p2_DLen2",
          "RailCD_uPeakRaw__u_DLen1",
          "PFlt_rSotChrg_mp__r1_DLen2",
          "PFlt_stExhGsChrg__OneToOne_DLen1",
          "PFlt_stCritDrv__OneToOne_DLen1",
          "PFltCD_pDiff__p3_DLen1",
          "CoEng_volFlConsum__OneToOne_DLen1",
          "ACCtl_stHys__OneToOne_DLen1",
          "PFltCD_tPre__t1_DLen1",
          "GlwCtl_stLogic__OneToOne_DLen1",
          "Unknown",
          "APPCD_stKickDwnSens__OneToOne_DLen1",
          "Unknown",
          "Unknown",
          "Unknown",
          "EGT_st__OneToOne_DLen4",
          "EGT_st__ShftR8_DLen4",
          "EGT_st__ShftR16_DLen4",
          "EGT_st__ShftR24_DLen4",
          "CrSCD_stIncErr_mp__OneToOne_DLen1",
          "CrSCD_stIncSyncInc_mp__OneToOne_DLen1",
          "MeUnCD_dcycOut_mp__r1_DLen1",
          "MeUn_iSet_mp__i1_DLen1",
          "MeUnCD_uRawVal_mp__u_DLen1",
          "InjCrv_stPiI1_mp__OneToOne_DLen1",
          "Unknown",
          "InjCrv_stPoI1_mp__OneToOne_DLen1",
          "FrmMng_stAddPmpDef__OneToOne_DLen1",
          "AddPmp_st__OneToOne_DLen1",
          "InjVlv_stErrBnk1__OneToOne_DLen1",
          "InjVlv_stErrBnk2__OneToOne_DLen1",
          "PFlt_pChrgMinThrEOBD__Carb_p2_DLen2",
          "PFlt_pChrgMaxThrEOBD__Carb_p2_DLen2",
          "InjVlv_nCyl1__n1_DLen2",
          "InjVlv_nCyl2__n1_DLen2",
          "InjVlv_nCyl3__n1_DLen2",
          "InjVlv_nCyl4__n1_DLen2",
          "InjVlv_qFBCCyl1__q1_DLen2",
          "InjVlv_qFBCCyl2__q1_DLen2",
          "InjVlv_qFBCCyl3__q1_DLen2",
          "InjVlv_qFBCCyl4__q1_DLen2",
          "Unknown",
          "FrmMng_stPrpErr__OneToOne_DLen2",
          "FrmMng_stPrpErr__ShftR8_DLen2",
          "FrmMng_stPrpReq__OneToOne_DLen1",
          "FrmMng_vPrpReq__Carb_v_DLen1",
          "PrpCtl_stShOff__OneToOne_DLen1",
          "CrCtl_stShutOffirev__OneToOne_DLen1",
          "CrCtl_stShutOffrev__OneToOne_DLen4",
          "CrCtl_stShutOffrev__ShftR8_DLen4",
          "AirSys_stLrn__OneToOne_DLen2",
          "AirSys_stLrn__ShftR8_DLen2",
          "CABSCD_uRaw__u_DLen2",
          "CABSCD_rRelPos__r1_DLen2",
          "CABCD_rOut__r1_DLen2",
          "AOHVCD_stOut__OneToOne_DLen1",
          "TVACD_rOut__r1_DLen2",
          "TVASCD_uRaw__u_DLen2",
          "TVASCD_rRelPos__r1_DLen2",
          "Unknown",
          "Unknown",
          "BPACD_rOut__r1_DLen2",
          "EGRSCD_uRaw__u_DLen2",
          "EGRSCD_rRelPos__r1_DLen2",
          "EGRCD_rOut__r1_DLen2",
          "CTSCD_tClntLin__t1_DLen2",
          "BPSCD_pLin__p1_DLen2",
          "IATSCD_tAirLin__t1_DLen2",
          "APPCD_rLinAPP1__r1_DLen2",
          "AFSCD_tAir__t1_DLen2",
          "InjCrv_qPoI2Des__q_DLen1",
          "InjCrv_phiPoI2Des__phi_DLen1",
          "InjCrv_tiPoI2Des__ti_DLen1",
          "PFltCD_uPresDiff__u_DLen1",
          "VSACD_rOut__r1_DLen1",
          "AirCtl_rCAB__r_DLen1",
          "EGRSCD_stOfsLrnStMch_mp__OneToOne_DLen1",
          "TVASCD_stOfsLrnStMch_mp__OneToOne_DLen1",
          "CABSCD_stOfsLrnStMch_mp__OneToOne_DLen1",
          "InjCrv_phiPiI1Conv_mp__phi_DLen1",
          "InjCrv_phiPoI2Conv_mp__phi_DLen1",
          "StSys_stEng__OneToOne_DLen1",
          "StSys_stActrOut__OneToOne_DLen1",
          "FrmMng_stStrt__OneToOne_DLen1",
          "T15CD_stElec__OneToOne_DLen1",
          "FrmMng_stWakeUp__OneToOne_DLen1",
          "Unknown"
  };

  private DTC dtc;
  private byte[] memory;
  private DTCInfo dtcInfo;

  public DTCEnv(DTC dtc, DTCInfo dtcInfo, byte[] memory) {

    this.dtc = dtc;
    this.memory = memory;
    this.dtcInfo = dtcInfo;

  }

  public int getDTCIdx() {
    return dtc.idx;
  }

  public String getCode(int n) {
    if(n==0) {
      return dtc.getbaseCode();
    } else {
      return dtc.getCode(n-1);
    }
  }

  public int getEnv(int n) {
    return dtc.getEnv(n);
  }

  public void apply(int[] envs) {
    dtc.setEnv(envs);
  }

}